import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { strToU8, zipSync } from "fflate";
import { z } from "zod";

const checklistItemSchema = z.object({
  label: z.string().trim().min(1).max(120),
  detail: z.string().trim().max(240),
  complete: z.boolean(),
});

const boothReadySnapshotSchema = z.object({
  score: z.number().int().min(0).max(100),
  lyricScore: z.number().int().min(0).max(100),
  performanceScore: z.number().int().min(0).max(100),
  nextAction: z.string().trim().max(300),
  checklist: z.array(checklistItemSchema).max(12),
  improvements: z.array(z.string().trim().min(1).max(300)).max(12),
  metrics: z.record(z.string(), z.number().int().min(0).max(100)),
});

export const boothExportSnapshotSchema = z.object({
  projectTitle: z.string().trim().min(1).max(160),
  artistName: z.string().trim().min(1).max(120),
  activeSection: z.string().trim().min(1).max(60),
  sections: z.record(z.string(), z.string().max(50_000)),
  beat: z.record(z.string(), z.unknown()).default({}),
  boothReady: boothReadySnapshotSchema,
  completionPct: z.number().int().min(0).max(100),
  totalBars: z.number().int().min(0).max(20_000),
  roughTake: z
    .object({
      id: z.string().uuid(),
      sectionName: z.string().trim().min(1).max(60),
      durationSeconds: z.number().int().min(0).max(3600),
      analysis: z.record(z.string(), z.unknown()).default({}),
    })
    .nullable()
    .default(null),
});

export const boothExportCreateSchema = z.object({
  project_id: z.string().uuid(),
  song_id: z.string().uuid(),
  session_id: z.string().uuid().nullable().optional(),
  rough_take_id: z.string().uuid().nullable().optional(),
  title: z.string().trim().min(1).max(160),
  snapshot: boothExportSnapshotSchema,
});

export type BoothExportSnapshot = z.infer<typeof boothExportSnapshotSchema>;

export type BoothExportRecord = {
  id: string;
  project_id: string;
  song_id: string;
  session_id: string | null;
  rough_take_id: string | null;
  version_number: number;
  title: string;
  booth_score: number;
  completion_pct: number;
  total_bars: number;
  snapshot: BoothExportSnapshot;
  created_at: string;
};

const SECTION_ORDER = ["Hook", "Verse 1", "Verse 2", "Bridge", "Outro"];
const GOLD = rgb(0.94, 0.63, 0.13);
const INK = rgb(0.08, 0.08, 0.09);
const MUTED = rgb(0.38, 0.38, 0.41);
const LINE = rgb(0.86, 0.86, 0.87);

export function boothExportFileStem(record: BoothExportRecord) {
  const safe = record.title
    .normalize("NFKD")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 80);
  return `${safe || "untitled-song"}-booth-v${record.version_number}`;
}

export function buildBoothLyricsText(record: BoothExportRecord) {
  const snapshot = record.snapshot;
  const beatTitle = textValue(snapshot.beat.title) || "No beat selected";
  const producer = textValue(snapshot.beat.producer) || "Not listed";
  const header = [
    "RAPWRITER.AI - BOOTH READY LYRIC SHEET",
    record.title,
    `Artist: ${snapshot.artistName}`,
    `Project: ${snapshot.projectTitle}`,
    `Beat: ${beatTitle}`,
    `Producer: ${producer}`,
    `Booth Ready: ${record.booth_score}/100`,
    `Version: ${record.version_number}`,
    `Exported: ${formatExportDate(record.created_at)}`,
  ];
  const sections = orderedSections(snapshot.sections).flatMap(([name, content]) => ["", name.toUpperCase(), content.trim() || "[Not written]"]);
  return [...header, ...sections, "", "Generated by RapWriter.ai"].join("\n");
}

export function buildBoothCreditsText(record: BoothExportRecord) {
  const beat = record.snapshot.beat;
  return [
    "RAPWRITER.AI - SESSION CREDITS",
    `Song: ${record.title}`,
    `Artist: ${record.snapshot.artistName}`,
    `Project: ${record.snapshot.projectTitle}`,
    `Beat: ${textValue(beat.title) || "No beat selected"}`,
    `Producer: ${textValue(beat.producer) || "Not listed"}`,
    `BPM: ${numberValue(beat.bpm) ?? "Not listed"}`,
    `Key: ${textValue(beat.key) || textValue(beat.musical_key) || "Not listed"}`,
    `License: ${textValue(beat.license) || "Verify before release"}`,
    "",
    "RapWriter stores this credit note as session metadata. Confirm all names, splits, and license terms before release.",
  ].join("\n");
}

export async function buildBoothPdf(record: BoothExportRecord) {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${record.title} - Booth Ready v${record.version_number}`);
  pdf.setAuthor(record.snapshot.artistName);
  pdf.setCreator("RapWriter.ai");
  pdf.setSubject("Booth Ready lyric and session handoff");

  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);
  const pageSize: [number, number] = [612, 792];
  const margin = 52;
  let page = pdf.addPage(pageSize);
  let y = 742;

  const addPage = () => {
    page = pdf.addPage(pageSize);
    drawPageHeader(page, record, bold);
    y = 716;
  };
  const ensure = (height: number) => {
    if (y - height < 48) addPage();
  };
  const line = (value: string, options: { font?: PDFFont; size?: number; color?: ReturnType<typeof rgb>; gap?: number; indent?: number } = {}) => {
    const font = options.font ?? regular;
    const size = options.size ?? 10.5;
    const gap = options.gap ?? 5;
    const indent = options.indent ?? 0;
    const rows = wrapPdfText(value, font, size, pageSize[0] - margin * 2 - indent);
    ensure(rows.length * (size + gap) + 4);
    for (const row of rows) {
      page.drawText(row, { x: margin + indent, y, font, size, color: options.color ?? INK });
      y -= size + gap;
    }
  };

  page.drawRectangle({ x: 0, y: 0, width: pageSize[0], height: pageSize[1], color: INK });
  page.drawRectangle({ x: margin, y: 584, width: pageSize[0] - margin * 2, height: 3, color: GOLD });
  page.drawText("RAPWRITER.AI", { x: margin, y: 728, font: bold, size: 12, color: GOLD });
  page.drawText("BOOTH READY SESSION", { x: margin, y: 705, font: regular, size: 9, color: rgb(0.73, 0.73, 0.75) });
  page.drawText(record.title, { x: margin, y: 650, font: bold, size: fitTitleSize(record.title), color: rgb(1, 1, 1) });
  page.drawText(`${record.snapshot.artistName}  /  ${record.snapshot.projectTitle}`, { x: margin, y: 618, font: regular, size: 11, color: rgb(0.72, 0.72, 0.74) });
  page.drawText(String(record.booth_score), { x: margin, y: 520, font: bold, size: 48, color: GOLD });
  page.drawText("/100 BOOTH READY", { x: margin + 64, y: 531, font: bold, size: 10, color: rgb(0.82, 0.82, 0.84) });
  page.drawText(`${record.total_bars} bars  /  ${record.completion_pct}% complete  /  version ${record.version_number}`, { x: margin, y: 485, font: regular, size: 10, color: rgb(0.72, 0.72, 0.74) });
  page.drawText(`Created ${formatExportDate(record.created_at)}`, { x: margin, y: 459, font: regular, size: 9, color: rgb(0.56, 0.56, 0.59) });

  addPage();
  sectionTitle(page, "SESSION NOTES", y, bold);
  y -= 26;
  line(record.snapshot.boothReady.nextAction || "No next action recorded.", { size: 11 });
  y -= 10;
  const beat = record.snapshot.beat;
  line(`Beat: ${textValue(beat.title) || "No beat selected"}`, { font: bold });
  line(`Producer: ${textValue(beat.producer) || "Not listed"}`);
  line(`BPM / Key: ${numberValue(beat.bpm) ?? "-"} / ${textValue(beat.key) || textValue(beat.musical_key) || "-"}`);
  line(`License: ${textValue(beat.license) || "Verify before release"}`);
  y -= 12;
  sectionTitle(page, "READINESS CHECK", y, bold);
  y -= 25;
  for (const item of record.snapshot.boothReady.checklist) {
    line(`${item.complete ? "READY" : "NEXT"}  ${item.label}`, { font: bold, color: item.complete ? rgb(0.12, 0.45, 0.27) : INK });
    line(item.detail, { color: MUTED, indent: 18 });
    y -= 4;
  }

  const writtenSections = orderedSections(record.snapshot.sections).filter(([, content]) => content.trim());
  for (const [name, content] of writtenSections) {
    addPage();
    sectionTitle(page, name.toUpperCase(), y, bold);
    y -= 30;
    const lyricLines = content.split(/\r?\n/);
    lyricLines.forEach((lyric, index) => {
      const rows = wrapPdfText(lyric || " ", mono, 11, pageSize[0] - margin * 2 - 30);
      ensure(rows.length * 18 + 4);
      page.drawText(String(index + 1).padStart(2, "0"), { x: margin, y, font: mono, size: 8.5, color: MUTED });
      rows.forEach((row, rowIndex) => {
        page.drawText(row, { x: margin + 30, y: y - rowIndex * 18, font: mono, size: 11, color: INK });
      });
      y -= Math.max(1, rows.length) * 18;
      page.drawLine({ start: { x: margin + 30, y: y + 7 }, end: { x: pageSize[0] - margin, y: y + 7 }, thickness: 0.45, color: LINE });
    });
  }

  return pdf.save();
}

export async function buildBoothZip(record: BoothExportRecord) {
  const stem = boothExportFileStem(record);
  const pdf = await buildBoothPdf(record);
  const sessionJson = JSON.stringify({
    exportId: record.id,
    version: record.version_number,
    title: record.title,
    boothScore: record.booth_score,
    completionPct: record.completion_pct,
    totalBars: record.total_bars,
    createdAt: record.created_at,
    snapshot: record.snapshot,
  }, null, 2);
  return zipSync({
    [`${stem}.pdf`]: pdf,
    [`${stem}-lyrics.txt`]: strToU8(buildBoothLyricsText(record)),
    [`${stem}-credits.txt`]: strToU8(buildBoothCreditsText(record)),
    [`${stem}-session.json`]: strToU8(sessionJson),
  }, { level: 6 });
}

function orderedSections(sections: Record<string, string>) {
  const known = SECTION_ORDER.filter((name) => Object.prototype.hasOwnProperty.call(sections, name)).map((name) => [name, sections[name] ?? ""] as const);
  const extra = Object.entries(sections).filter(([name]) => !SECTION_ORDER.includes(name));
  return [...known, ...extra];
}

function textValue(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

function numberValue(value: unknown) {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function formatExportDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toISOString().replace("T", " ").slice(0, 16) + " UTC";
}

function fitTitleSize(title: string) {
  if (title.length > 48) return 24;
  if (title.length > 32) return 29;
  return 34;
}

function drawPageHeader(page: PDFPage, record: BoothExportRecord, font: PDFFont) {
  page.drawText("RAPWRITER.AI", { x: 52, y: 748, font, size: 8.5, color: GOLD });
  page.drawText(`${record.title}  /  V${record.version_number}`, { x: 370, y: 748, font, size: 7.5, color: MUTED });
  page.drawLine({ start: { x: 52, y: 738 }, end: { x: 560, y: 738 }, thickness: 1, color: GOLD });
}

function sectionTitle(page: PDFPage, value: string, y: number, font: PDFFont) {
  page.drawText(value, { x: 52, y, font, size: 13, color: INK });
  page.drawLine({ start: { x: 52, y: y - 9 }, end: { x: 560, y: y - 9 }, thickness: 1, color: GOLD });
}

function wrapPdfText(value: string, font: PDFFont, size: number, maxWidth: number) {
  const words = value.replace(/[^\x20-\x7E]/g, "'").split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth || !line) line = candidate;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line || lines.length === 0) lines.push(line);
  return lines;
}
