"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Inbox, Loader2, MessageSquare, Paperclip, RefreshCw, Send, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { supportCategoryLabel, supportPriorities, supportStatuses } from "@/lib/support";
import { cn } from "@/lib/utils";

type QueueTicket = { id: string; ticket_number: string; owner_id: string; category: string; subject: string; customer: string; status: string; priority: string; assigned_to: string | null; created_at: string; updated_at: string };
type QueuePayload = { tickets: QueueTicket[]; metrics: { open: number; needs_reply: number; waiting_on_customer: number; resolved_today: number }; staff: Array<{ id: string; email: string; role: string }>; current_staff_id: string | null };
type DetailPayload = { ticket: QueueTicket & Record<string, unknown>; messages: Array<{ id: string; sender_type: string; body: string; created_at: string }>; attachments: Array<{ id: string; file_name: string; signed_url: string | null }>; internal_notes: Array<{ id: string; body: string; created_at: string }>; events: Array<{ id: number; event_type: string; from_value: string | null; to_value: string | null; created_at: string }>; customer: { email: string | null; roles: string[] }; producer: { display_name: string; status: string; verified: boolean } | null; order: { order_number: string; status: string; total_cents: number; currency: string } | null };

export function AdminSupportCenter() {
  const [payload, setPayload] = useState<QueuePayload | null>(null);
  const [detail, setDetail] = useState<DetailPayload | null>(null);
  const [filter, setFilter] = useState("active");
  const [reply, setReply] = useState("");
  const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const visible = useMemo(() => (payload?.tickets ?? []).filter((ticket) => filter === "all" || (filter === "active" ? !["resolved", "closed"].includes(ticket.status) : ticket.status === filter)), [filter, payload]);

  async function loadQueue() { setLoading(true); const response = await fetch("/api/admin/support", { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (response.ok) setPayload(data); else toast.error(data.error ?? "Support queue could not load."); setLoading(false); }
  async function loadDetail(id: string) { setBusy(true); const response = await fetch(`/api/admin/support?ticket_id=${id}`, { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (response.ok) setDetail(data); else toast.error(data.error ?? "Ticket could not load."); setBusy(false); }
  useEffect(() => { void loadQueue(); }, []);
  async function action(input: Record<string, unknown>, message: string) { if (!detail) return; setBusy(true); const response = await fetch(`/api/admin/support?ticket_id=${detail.ticket.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const data = await response.json().catch(() => ({})); if (response.ok) { setReply(""); setNote(""); await Promise.all([loadQueue(), loadDetail(detail.ticket.id)]); toast.success(message); } else toast.error(data.error ?? "Support action failed."); setBusy(false); }

  return <section className="panel mt-5 rounded-3xl p-5">
    <div className="flex items-start justify-between gap-4"><div><div className="label-hw text-gold">Support</div><h2 className="mt-2 text-2xl font-semibold">Customer Support</h2><p className="mt-2 text-sm text-muted-foreground">Conversations, account context, and case history in one queue.</p></div><button onClick={() => void loadQueue()} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10" aria-label="Refresh support queue"><RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} /></button></div>
    <div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4">{[[Inbox,"Open",payload?.metrics.open ?? 0],[MessageSquare,"Needs reply",payload?.metrics.needs_reply ?? 0],[Clock3,"Waiting",payload?.metrics.waiting_on_customer ?? 0],[CheckCircle2,"Resolved today",payload?.metrics.resolved_today ?? 0]].map(([Icon,label,value]) => { const StatIcon = Icon as typeof Inbox; return <div key={String(label)} className="rounded-xl border border-white/10 bg-black/25 p-3"><StatIcon className="h-4 w-4 text-gold" /><div className="mt-3 text-xl font-semibold">{String(value)}</div><div className="mt-1 text-[10px] text-muted-foreground">{String(label)}</div></div>; })}</div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{["active","open","in_progress","waiting_on_customer","resolved","closed","all"].map((item) => <button key={item} onClick={() => setFilter(item)} className={cn("shrink-0 rounded-full border px-3 py-2 text-[10px] font-semibold", filter === item ? "border-gold/40 bg-gold/10 text-gold" : "border-white/10 text-white/45")}>{item.replaceAll("_"," ")}</button>)}</div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[0.9fr_1.35fr]">
      <div className="max-h-[680px] space-y-2 overflow-y-auto pr-1">{loading ? <Loader2 className="mx-auto mt-12 h-5 w-5 animate-spin text-gold" /> : visible.length ? visible.map((ticket) => <button key={ticket.id} onClick={() => void loadDetail(ticket.id)} className={cn("w-full rounded-xl border p-3 text-left", detail?.ticket.id === ticket.id ? "border-gold/35 bg-gold/[0.06]" : "border-white/10 bg-black/20")}><div className="flex justify-between gap-2"><span className="text-[10px] font-semibold text-gold">{ticket.ticket_number}</span><span className="text-[9px] uppercase text-white/45">{ticket.priority}</span></div><div className="mt-2 truncate text-sm font-semibold">{ticket.subject}</div><div className="mt-2 truncate text-[10px] text-muted-foreground">{ticket.customer} · {ticket.status.replaceAll("_"," ")}</div></button>) : <div className="rounded-xl border border-white/10 p-6 text-center text-sm text-muted-foreground">Queue is clear.</div>}</div>
      <div className="min-h-64 rounded-2xl border border-white/10 bg-black/20 p-4">{detail ? <SupportDetail detail={detail} staff={payload?.staff ?? []} currentStaffId={payload?.current_staff_id ?? null} reply={reply} note={note} busy={busy} onReply={setReply} onNote={setNote} onAction={action} /> : <div className="grid min-h-64 place-items-center text-center"><div><ShieldCheck className="mx-auto h-6 w-6 text-gold" /><p className="mt-3 text-sm text-muted-foreground">Select a ticket to open the secure case record.</p></div></div>}</div>
    </div>
  </section>;
}

function SupportDetail({ detail, staff, currentStaffId, reply, note, busy, onReply, onNote, onAction }: { detail: DetailPayload; staff: QueuePayload["staff"]; currentStaffId: string | null; reply: string; note: string; busy: boolean; onReply: (value: string) => void; onNote: (value: string) => void; onAction: (input: Record<string, unknown>, message: string) => Promise<void> }) {
  const ticket = detail.ticket;
  return <div><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-semibold text-gold">{ticket.ticket_number}</div><h3 className="mt-1 text-xl font-semibold">{ticket.subject}</h3><p className="mt-1 text-xs text-muted-foreground">{supportCategoryLabel(String(ticket.category))} · {detail.customer.email ?? "Unknown customer"}</p></div><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] uppercase text-white/55">{String(ticket.status).replaceAll("_"," ")}</span></div>
    <div className="mt-4 grid grid-cols-2 gap-2 text-[10px]"><Context label="Membership" value={membershipLabel(ticket.membership_snapshot)} /><Context label="Entitlement" value={String(ticket.entitlement_source ?? "free")} /><Context label="Platform" value={`${String(ticket.platform)} · ${String(ticket.app_version ?? "unknown")}`} /><Context label="Producer" value={detail.producer ? `${detail.producer.display_name} · ${detail.producer.status}` : "Not active"} />{detail.order && <Context label="Order" value={`${detail.order.order_number} · ${detail.order.status}`} />}</div>
    <div className="mt-4 grid grid-cols-3 gap-2"><select value={String(ticket.status)} onChange={(event) => void onAction({ action: "status", status: event.target.value }, "Ticket status updated")} disabled={busy} className="min-h-10 rounded-xl border border-white/10 bg-[#09090a] px-2 text-[10px]">{supportStatuses.map((item) => <option key={item}>{item}</option>)}</select><select value={String(ticket.priority)} onChange={(event) => void onAction({ action: "priority", priority: event.target.value }, "Priority updated")} disabled={busy} className="min-h-10 rounded-xl border border-white/10 bg-[#09090a] px-2 text-[10px]">{supportPriorities.map((item) => <option key={item}>{item}</option>)}</select><select value={String(ticket.assigned_to ?? "")} onChange={(event) => void onAction({ action: "assign", assigned_to: event.target.value || null }, "Assignment updated")} disabled={busy} className="min-h-10 rounded-xl border border-white/10 bg-[#09090a] px-2 text-[10px]"><option value="">Unassigned</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.id === currentStaffId ? "Me" : member.email}</option>)}</select></div>
    <div className="mt-4 max-h-72 space-y-2 overflow-y-auto rounded-xl border border-white/10 p-3"><div className="rounded-xl bg-white/[0.04] p-3"><div className="text-[9px] font-semibold text-gold">CUSTOMER</div><p className="mt-1 text-sm leading-6">{String(ticket.description)}</p></div>{detail.messages.map((message) => <div key={message.id} className={cn("max-w-[90%] rounded-xl p-3", message.sender_type === "support" ? "ml-auto bg-gold/10" : "bg-white/[0.04]")}><div className="text-[9px] font-semibold text-gold">{message.sender_type === "support" ? "SUPPORT" : "CUSTOMER"}</div><p className="mt-1 text-sm leading-6">{message.body}</p></div>)}</div>
    {detail.attachments.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{detail.attachments.map((item) => <a key={item.id} href={item.signed_url ?? "#"} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-[10px]"><Paperclip className="h-3 w-3 text-gold" />{item.file_name}</a>)}</div>}
    <div className="mt-4"><textarea value={reply} onChange={(event) => onReply(event.target.value)} placeholder="Reply to customer" className="min-h-24 w-full resize-none rounded-xl border border-white/10 bg-black/30 p-3 text-sm outline-none focus:border-gold/35" /><button onClick={() => void onAction({ action: "reply", body: reply }, "Support reply sent")} disabled={busy || !reply.trim()} className="gold-seal mt-2 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl text-xs font-semibold disabled:opacity-35"><Send className="h-3.5 w-3.5" />Reply and wait for customer</button></div>
    <details className="mt-3 rounded-xl border border-white/10 p-3"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-semibold"><UserRound className="h-4 w-4 text-gold" />Internal notes ({detail.internal_notes.length})</summary><div className="mt-3 space-y-2">{detail.internal_notes.map((item) => <div key={item.id} className="rounded-lg bg-white/[0.035] p-2 text-xs text-white/65">{item.body}</div>)}<textarea value={note} onChange={(event) => onNote(event.target.value)} placeholder="Private staff note" className="min-h-20 w-full resize-none rounded-lg border border-white/10 bg-black/30 p-2 text-xs outline-none" /><button onClick={() => void onAction({ action: "internal_note", body: note }, "Internal note added")} disabled={busy || !note.trim()} className="min-h-9 w-full rounded-lg border border-gold/25 text-[10px] font-semibold text-gold disabled:opacity-35">Add private note</button></div></details>
    <details className="mt-3 rounded-xl border border-white/10 p-3"><summary className="cursor-pointer text-xs font-semibold">Ticket history ({detail.events.length})</summary><div className="mt-3 space-y-2">{detail.events.map((event) => <div key={event.id} className="text-[10px] text-muted-foreground">{event.event_type.replaceAll("_"," ")} {event.to_value ? `→ ${event.to_value}` : ""} · {new Date(event.created_at).toLocaleString()}</div>)}</div></details>
  </div>;
}
function Context({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[0.025] p-2"><div className="text-white/35">{label}</div><div className="mt-1 truncate font-semibold text-white/70">{value}</div></div>; }
function membershipLabel(value: unknown) { if (!value || typeof value !== "object") return "Free"; const snapshot = value as { artist?: { plan_name?: string } | null; producer?: { plan_name?: string } | null }; return [snapshot.artist?.plan_name, snapshot.producer?.plan_name].filter(Boolean).join(" / ") || "Free"; }
